# Alpine-based Autopilot Pattern implementation
# http://autopilotpattern.io/

nagios:
    image: prato/autopilot-base:0.2.0
    labels:
      - triton.cns.services=nagios
    mem_limit: 128m
    restart: always
    env_file: _env
    command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      /bin/sh
